### ISSUE TITLE
Problem indexing websites

### ISSUE THREAD

**Issue by PythonMen** [opensemanticsearch/open-semantic-search#124]
I'm trying to index a website using the server tool on Debian Linux VM.

 I've tried using the UI on the web browser, but it only manages to index a single web page even with a sitemap.xml. I've tried using console commands opensemanticsearch-index-web and opensemanticsearch-index-sitemap, however none seem to work. It adds the sites to the queue, but they never start downloading. 

I've left the PC on over night to see if it just took him long, but nothing. Indexing folders seems to work just fine though.

 Any help would be appreachiated.

**Comment by Mandalka** [comment]
You have to use opensemanticsearch-index-web-crawl if you want to crawl all subpaths of the url) instead of opensemanticsearch-index-web for only a singe URL.

If indexing by Datasources web UI you have to switch option "How much to crawl" from "Index only this webpage" to "Crawl all webpages whthin this path".

One problem can be: If You config http://mydomain.test and it redirects or links to https://mydomain.test it is not crawled deeper than the first page until you switch protocoll and domain to the protocoll and domain that is linked in the result.

Additionally opensemanticsearch-index-web-crawl  had a bug on some especially newer Scrapy, Python or Linux installations which was fixed in https://github.com/opensemanticsearch/open-semantic-search/issues/215 and will be available in todays release.

**Comment by fractalvision** [comment]
The problem still persists, the app doesn't crawl further than the index page even starting from the very site root and with "Crawl full domain and subdomains" option enabled.
